apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgABC4sonYb2JlSTzG2ZGEVTCbOqvUDbUe8idszJpuFIlCqMNJE+5H1717XFERxHOurBsDQfQ+qI191QT0jhFdR+OE23EEm1srdJzoqFNnTtqtmJEBDMYJM5uhc2ze1/pjAlKOMessW5m5hF60iNmtMwucD59pZipGLtaOXyBIDS8ZEiGGsNrAWB6cAsWgy4T2A9GcJ1bPwRnUZ3GIJhkx6WXnd3Kdp6u3tn4T0w4ZQXrYY9i0Q2mFjDg/woJmYbqMDc4JTkDt+hgTw9KhDzQnUkDyo2yUjtf+1jyW8u9N+MZauhLq8AD+LvaCgID3epholJX6cwn9X8cSKvJvKr3uIZE2dBXU6it3V0R3G7Cc+h8Unkqy+O1ri6Z6NWWpNoyC4yI+6fqInDAlWbQGGoA6Ns8f+QflXalCLced7oASALjz6HVG3qm8/qG10k8iQBUH7/6IB4Jl5NRKbV1TymrHoAUVQHw+aIDRMJbyxZBgd+fbtLExDCqaYGIN+p8cSivghYbkkHBPFB0Q81fY6VByRO8O2OtsT5ZuNAFV/rzQIPRqJunWQSBU5+rAgQK1tt8nS+XXWF5VOInoQTGDg96tHWZhq3TYZRGDU/QmJD2hj/riNvh4/As48kV30MlS8FzGUMd34YI8ZUT70FMRuDCvADiAUMGK6KfP3c8D8RGhhNK5gNyqMb70Xz8g6n8cNU4AoKYaicSjBvj9+jv9t1UV/RXOzVeL+fxckG+Fp64zuv+dQBe40srn8ifETGznDRx6L8PWgP+sLpkYhfwnfk0+pHppfO+LteyRFcVFSV7Lyng1zO7TIqJbUaQbRVIOh3ACjN1rsw/HIn8JPHySYyXQP1p5nlTUO48NbJt30eFgzkojQru0QR4ermaO590HgEWQ4VEHvHLKZM6uSHoRtaEu9jt/SFgkHlSLvBt8Ktd729ry8XRngg9pAq/McNO0aryTGRpWYrhV8KiJz0Sdc1lAkx+fadqMA1ouQWoh1UlQ1j8qMirxHrwrt8LBMN0xWQCPMT59qFlzmyoiS7cCo3lC8nnJKd4qwsR0Y9XmKWeTm/ZorR8h4cOcCxA2lLoqLVYyNHE4XGe1ulanx+yzlntjuy7SDoaxrMKkDgSsJ+EAh4Yw7jln55pJXOtZhTNT+/J8Isv5PCso3a2eF4nALbxsWOc9KJBziABHEV86ZEXVwLLqvnvxrZt+GqXIYGhu7daDNuwNb1hc8Mo2eQZgHJOKLoHH45Kz0QR4xA6DTOz17qx+fwsKOUrK8WfMs5Th17uwhjK9qMzXchoFmAupMpEnhx4lKOLfprNIx9buAu20zBgC4usKr6inhmRilwV32PfaGi
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

