apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ace
  spec:
    commonName: appdomain.cloud
    dnsNames:
    - '*.itzroks-5500059ths-n1u8bw-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud'
    isCA: false
    issuerRef:
      kind: ClusterIssuer
      name: ca-issuer
    keystores:
      jks:
        create: true
        passwordSecretRef:
          key: password
          name: ace-jks-password
    secretName: ace-key-pair
    subject:
      countries:
      - GB
      localities:
      - London
      organizationalUnits:
      - Assets and Architecture
      organizations:
      - IBM
      provinces:
      - London
kind: List
metadata: {}
