apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ca
  spec:
    commonName: ${COMMON_NAME}
    dnsNames:
    - '*.itzroks-5500059ths-unonwt-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud'
    isCA: true
    issuerRef:
      kind: Issuer
      name: root-issuer
    secretName: ca-key-pair
    subject:
      countries:
      - GB
      localities:
      - London
      organizationalUnits:
      - Assets and Architecture
      organizations:
      - IBM
      provinces:
      - London
kind: List
metadata: {}
