apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ace
  spec:
    commonName: appdomain.cloud
    dnsNames:
    - '*.itzroks-5500059ths-unonwt-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-gb.containers.appdomain.cloud'
    isCA: true
    issuerRef:
      kind: Issuer
      name: prod-ref-ss
    secretName: ace-tls-key-pair
    subject:
      countries:
      - GB
      localities:
      - London
      organizationalUnits:
      - ACE
      organizations:
      - IBM
      provinces:
      - London
kind: List
metadata: {}
