apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ace-jks-password
spec:
  encryptedData:
    password: AgAjj7iubfCk3ge26aOdfnZUO+rB5qfMBuY0PoBQNICVX7howKm+K3fQymfBEze4jULQ4EIp/vXCv0o/aBOVBN7aU3HnUcs5jXovTI4oia/eo7QACl/7KTFUXNuKbcqxlrBrcfxHpH8V4nqPqK2db+2KVop9tVqHONl3v9ze5TxnH/CE7sHfDty1fx1GKppKpvs8aHClCsHtMWINbv6lTAfGN1MzpnFzdTdPpmJrTF20CewKKXz5yjDbEKw4as6g36pF8B1F8MuDqkqzwTfv2tj1IIMzdrpIMfOddUCiXt4b086l5PtQ8VCS9bsYBlry24/5z6GsjnUbt1Id4Xh7xxHBibK2JvxeggNIXY4pfGcOUigF2mkQd7hsLb/X5lqHX8lo/OPuuVTMacRl3EXG7uCpiIRIJkJZcoVHGXeYhSXm+KerppOoU3wEJ5Wuz8Cw6cwPaQddeWV7DshcNKUcUdjvByEaU+90KUTR3w1SjwQoraInievBdjjgyuCszpndDoMyLKQ8ByijWkPNAHMz3xpg238UP6nAnZygZU3l8Cd9gomOuvxNemcofM17Jr6Mp70DWPUIgZBtsClWmSH0yqhsVTu/NK/aLmep0xleJbAXK0F+ZG3sKJt6msSE/UjwPaxqmwu3/FCGz9vRm+9d7r9WfZI2kL95KWAHbIhiknRKTnT/0o72pxLcLAI+zhCXV9rdFLX496jSUwbuZb8nC97S
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ace-jks-password

