apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: create-customer-keystore-setdbparms
spec:
  encryptedData:
    configuration: AgB2ctJ3R2649kLkJSVXE8Iiffitl6k4KruILv6dtPX/odEEngDEp6lt2X/WnfKZknP1gDCpg3lyVkJ80fz4fkZEuHBSWxDx6yQ8kDv4UpA95s+fHmonpNwci+Iq8KqWAQ6/gJlXuRCvGZGK9qZAQX7fLCkVhxbKYQOnIIoLXHrHJSEvCfcYuclO3+JCq8wJj3P0d1+BbrP3j9s3X+a4pLZSz76XlMaOoS40wYAps4WRgx4r4/CGgz6YGztOUmSsV2i9RzeLN+OXF5tw+GowALJgAVIyU50P9O5m2YTPji3jp2xS1m9y2wwvvvKI1t7ZcDSKbJM+KdDaJeGv3p0t3zNG5XMf+d/XxeC+z5URjgYqmjBFeoUdKiScEfHBWD76tDPTQNut0pYln83DjhiTPJJkCCEeWxlZuSdeuO0frhHBXeHuzM4CRD6t/AaFkN80LnGjTms5qhUKcmvUiWHMbgb+4vyhGBjj4MPu/GX28fbN2UJMm6UgJaX0OoM8AOyGDmSB739btljDlghdch1hNhqen56YRd+KD2l9tn8hnksNsuO7c3FwfHpysTnyWZzfV8vjdaNCKYslyCfwtDbza7v753k/OaMb3bjiiuVRr6kVWtjdehC701n5WWAaD9P6LOQSStLKIs2lDC6kpmeqDA0PkWXv3UsjR3s/iIjiUqX4TVDYBfUpeSmkjnu71O3cMaURzFt2VKlTWE2IIjPcGfoZWsq8YbaeSd7YhqRjPk3uHpdQZNeZiWK1k0qppHU+C44QfVIHFvYraw/bmg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: create-customer-keystore-setdbparms

